In [4]:
import pandas as pd

admission=pd.read_csv("Admission_Predict.csv")

admission


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [5]:
admission.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [21]:
import numpy as np

X=admission[['CGPA','University Rating','Research']]

Y=admission['Chance of Admit ']


In [22]:
from sklearn.model_selection import train_test_split


In [51]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [52]:
X_train.count()

CGPA                 300
University Rating    300
Research             300
dtype: int64

In [53]:
Y_train.count()

300

In [54]:
Y_test.count()

100

In [55]:
from sklearn.linear_model import LinearRegression

c=LinearRegression()

c.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
c.predict(X_test)

array([0.84898092, 0.93924463, 0.88424798, 0.68474663, 0.68401711,
       0.52565195, 0.5688842 , 0.82995873, 0.65223075, 0.68988624,
       0.511477  , 0.69339308, 0.52114534, 0.76977421, 0.7486821 ,
       0.82995873, 0.56542562, 0.91157599, 0.79364364, 0.6380558 ,
       0.5633557 , 0.93232747, 0.69200442, 0.75525863, 0.90465883,
       0.73937651, 0.66947539, 0.83202865, 0.90154088, 0.5861771 ,
       0.78360853, 0.62110353, 0.66053657, 0.52738124, 0.55125067,
       0.94270321, 0.63800754, 0.54155619, 0.47204396, 0.6968034 ,
       0.60381063, 0.85657934, 0.71621448, 0.89428309, 0.87906011,
       0.46166822, 0.8047489 , 0.64704288, 0.76804492, 0.68988624,
       0.71029709, 0.73311849, 0.56715491, 0.63493785, 0.75386997,
       0.77362168, 0.7127559 , 0.67298223, 0.61138693, 0.96033674,
       0.58924679, 0.52565195, 0.60726921, 0.76704515, 0.66740547,
       0.86661445, 0.55470925, 0.7411058 , 0.94304384, 0.73869525,
       0.73450715, 0.90154088, 0.50974771, 0.60692858, 0.79644

In [57]:
Y_test

68     0.68
284    0.94
285    0.93
295    0.68
379    0.71
       ... 
116    0.56
352    0.64
20     0.64
246    0.72
187    0.93
Name: Chance of Admit , Length: 100, dtype: float64

In [58]:
c.score(X_test,Y_test)

0.7570532075037095

In [59]:
c.predict(X_test)

array([0.84898092, 0.93924463, 0.88424798, 0.68474663, 0.68401711,
       0.52565195, 0.5688842 , 0.82995873, 0.65223075, 0.68988624,
       0.511477  , 0.69339308, 0.52114534, 0.76977421, 0.7486821 ,
       0.82995873, 0.56542562, 0.91157599, 0.79364364, 0.6380558 ,
       0.5633557 , 0.93232747, 0.69200442, 0.75525863, 0.90465883,
       0.73937651, 0.66947539, 0.83202865, 0.90154088, 0.5861771 ,
       0.78360853, 0.62110353, 0.66053657, 0.52738124, 0.55125067,
       0.94270321, 0.63800754, 0.54155619, 0.47204396, 0.6968034 ,
       0.60381063, 0.85657934, 0.71621448, 0.89428309, 0.87906011,
       0.46166822, 0.8047489 , 0.64704288, 0.76804492, 0.68988624,
       0.71029709, 0.73311849, 0.56715491, 0.63493785, 0.75386997,
       0.77362168, 0.7127559 , 0.67298223, 0.61138693, 0.96033674,
       0.58924679, 0.52565195, 0.60726921, 0.76704515, 0.66740547,
       0.86661445, 0.55470925, 0.7411058 , 0.94304384, 0.73869525,
       0.73450715, 0.90154088, 0.50974771, 0.60692858, 0.79644

In [60]:
c.predict(X_train)

array([0.63800754, 0.7486821 , 0.99665183, 0.62768006, 0.85312076,
       0.61384574, 0.82511149, 0.82995873, 0.7140963 , 0.61211645,
       0.48760757, 0.64185501, 0.84413368, 0.77116287, 0.78049058,
       0.9153752 , 0.84759226, 0.85312076, 0.77635074, 0.97071248,
       0.93612668, 0.72447204, 0.7300488 , 0.84898092, 0.47862049,
       0.71967306, 0.75214068, 0.68301734, 0.91710449, 0.78153861,
       0.92268125, 0.90292954, 0.54779209, 0.85450942, 0.86176721,
       0.60653969, 0.61038716, 0.56196704, 0.71755488, 0.69719229,
       0.66226586, 0.72140235, 0.7313892 , 0.73450715, 0.71241527,
       0.67091231, 0.79091458, 0.72135409, 0.73696596, 0.765975  ,
       0.64078486, 0.949961  , 0.87733082, 0.56715491, 0.97762964,
       0.98973467, 0.45786901, 0.61730432, 0.48553765, 0.72140235,
       0.79364364, 0.8178537 , 0.8351466 , 0.82857007, 0.94304384,
       0.82684078, 0.76568264, 0.66879413, 0.62456211, 0.56196704,
       0.71029709, 0.65218249, 0.87007303, 0.86488516, 0.89116

In [61]:
c.predict(X_test)

array([0.84898092, 0.93924463, 0.88424798, 0.68474663, 0.68401711,
       0.52565195, 0.5688842 , 0.82995873, 0.65223075, 0.68988624,
       0.511477  , 0.69339308, 0.52114534, 0.76977421, 0.7486821 ,
       0.82995873, 0.56542562, 0.91157599, 0.79364364, 0.6380558 ,
       0.5633557 , 0.93232747, 0.69200442, 0.75525863, 0.90465883,
       0.73937651, 0.66947539, 0.83202865, 0.90154088, 0.5861771 ,
       0.78360853, 0.62110353, 0.66053657, 0.52738124, 0.55125067,
       0.94270321, 0.63800754, 0.54155619, 0.47204396, 0.6968034 ,
       0.60381063, 0.85657934, 0.71621448, 0.89428309, 0.87906011,
       0.46166822, 0.8047489 , 0.64704288, 0.76804492, 0.68988624,
       0.71029709, 0.73311849, 0.56715491, 0.63493785, 0.75386997,
       0.77362168, 0.7127559 , 0.67298223, 0.61138693, 0.96033674,
       0.58924679, 0.52565195, 0.60726921, 0.76704515, 0.66740547,
       0.86661445, 0.55470925, 0.7411058 , 0.94304384, 0.73869525,
       0.73450715, 0.90154088, 0.50974771, 0.60692858, 0.79644

In [62]:
c.predict(Y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[0.68 0.94 0.93 0.68 0.71 0.58 0.68 0.83 0.54 0.74 0.56 0.7  0.45 0.69
 0.78 0.84 0.68 0.96 0.77 0.42 0.58 0.95 0.69 0.75 0.91 0.68 0.72 0.84
 0.93 0.48 0.77 0.72 0.62 0.38 0.51 0.93 0.65 0.36 0.47 0.62 0.63 0.88
 0.76 0.91 0.88 0.47 0.87 0.64 0.73 0.76 0.53 0.73 0.63 0.47 0.73 0.55
 0.73 0.72 0.52 0.95 0.64 0.57 0.62 0.76 0.73 0.9  0.52 0.77 0.94 0.75
 0.81 0.92 0.49 0.73 0.78 0.92 0.96 0.82 0.5  0.75 0.7  0.78 0.57 0.77
 0.95 0.94 0.86 0.69 0.64 0.64 0.57 0.44 0.64 0.76 0.71 0.56 0.64 0.64
 0.72 0.93].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [63]:
c.score(X_test,Y_test)

0.7570532075037095